#Лабораторна робота 1
###Студента групи МІТ-31 (підгрупа 1)
###Байди Данила Андрійовича
##Завдання
1. NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)).Використати arange, random.
2. Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))
3. Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)
4. Відповіді оформити .ipynb документом
5. Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab1 де має бути .ipynb файл та необхідні файли з даними

In [3]:
import numpy as np

import matplotlib as mpl

print("CRUD : numbers")
x = np.random.randint(0, 10)
y = np.random.randint(0, 10)
print("x = ", x)
print("y = ", y)
print("x+y = ", x+y)
print("x-y = ", x-y)
print("x*y = ", x*y)
print("x/y = ", x/y)

print()
print("CRUD : array")
print("Creation: ")
array1 = np.arange(10,50,4)
print(array1) 
array2 = np.random.randint(0, 100, 10)
print(array2)
print("Add new element into array2: ")
some_numb = np.random.randint(0, 100)
print("Some_number = ", some_numb)
array2 = np.append(array2, some_numb)
print(array2)
print("")
print("Reading first element of second array:")
print(array2.item(0), end="\n\n")

print("Deleting: delete array2 last element")
array2 = np.delete(array2, -1)
print(array2, end="\n\n")

print("Changing array_1 last element to some_number")
array1[-1] = some_numb
print(array1, end="\n\n")

print("multiplication: ")
array1 = np.multiply(array1, 1.1)
print(array1)
print("elevation to the degree: ")
array2 = np.power(array2, 3)
print(array2, end="\n\n")

print("Vector multiplication: ")
first_array = np.add(array1,array2)
second_array = np.subtract(array1,array2)
print(first_array)
print(second_array, end="\n\n")

first_matrix = np.random.randint(10, 100, size = (4,4))
second_matrix = np.random.randint(10, 100, size = (4,4))
print("Matrix 1: ")
print(first_matrix, sep="\n\n")
print("Matrix 2: ")
print(second_matrix, sep="\n\n")

print("SUM: ")
print(first_matrix+second_matrix)
print("DIFF: ")
print(first_matrix-second_matrix)
print("MULTI: ")
print(first_matrix*second_matrix)
print("DIVISION: ")
print(first_matrix/second_matrix)

CRUD : numbers
x =  6
y =  4
x+y =  10
x-y =  2
x*y =  24
x/y =  1.5

CRUD : array
Creation: 
[10 14 18 22 26 30 34 38 42 46]
[67 72 81 86  5 48 21 41 22 76]
Add new element into array2: 
Some_number =  64
[67 72 81 86  5 48 21 41 22 76 64]

Reading first element of second array:
67

Deleting: delete array2 last element
[67 72 81 86  5 48 21 41 22 76]

Changing array_1 last element to some_number
[10 14 18 22 26 30 34 38 42 64]

multiplication: 
[11.  15.4 19.8 24.2 28.6 33.  37.4 41.8 46.2 70.4]
elevation to the degree: 
[300763 373248 531441 636056    125 110592   9261  68921  10648 438976]

Vector multiplication: 
[3.007740e+05 3.732634e+05 5.314608e+05 6.360802e+05 1.536000e+02
 1.106250e+05 9.298400e+03 6.896280e+04 1.069420e+04 4.390464e+05]
[-3.007520e+05 -3.732326e+05 -5.314212e+05 -6.360318e+05 -9.640000e+01
 -1.105590e+05 -9.223600e+03 -6.887920e+04 -1.060180e+04 -4.389056e+05]

First_matrix: 
[[74 66 99 41]
 [56 77 87 67]
 [85 42 52 27]
 [52 93 74 55]]
Matrix 2: 
[[78 25 82 